basePath: /api/v1
definitions:
  CreateUserDto:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  ErrorResponse:
    properties:
      code:
        type: string
      fields:
        items:
          $ref: '#/definitions/FieldError'
        type: array
      message:
        type: string
    type: object
  FieldError:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  UserResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    required:
    - email
    - id
    type: object
host: localhost:8080
info:
  contact: {}
  description: URL Shortener management service.
  title: URL Shortener API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CreateUserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create User
      tags:
      - users
  /users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user by id
      tags:
      - users
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: '"Bearer <access_token>" format'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
