// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/yodzafar/url-shortener-service/internal/config"
	"github.com/yodzafar/url-shortener-service/internal/repository/postgres/repo"
	"github.com/yodzafar/url-shortener-service/internal/repository/postgres/sqlc"
	"github.com/yodzafar/url-shortener-service/internal/service"
	"github.com/yodzafar/url-shortener-service/internal/transport/http"
	"github.com/yodzafar/url-shortener-service/internal/transport/http/handler"
	"github.com/yodzafar/url-shortener-service/pkg/validator"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, cfg *config.Config) (*App, func(), error) {
	pool, cleanup, err := providePool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	queries := sqlc.New(pool)
	userRepository := repo.NewUserRepository(queries)
	bcrypt := provideHasher()
	userService := service.NewUserService(userRepository, bcrypt)
	validatorValidator, err := validator.New()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userHandler := handler.NewUserHandler(userService, validatorValidator)
	logger := providerLogger(cfg)
	routerDeps := http.RouterDeps{
		User:   userHandler,
		Logger: logger,
	}
	httpHandler := http.NewRouter(routerDeps)
	server := provideServer(cfg, httpHandler)
	app := NewApp(server, logger)
	return app, func() {
		cleanup()
	}, nil
}
